import { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { Box, ChevronDown, ChevronUp, Truck, Share2, Download, MessageCircle, Mail, Trash2, Plus } from 'lucide-react'
import { useEstimates, useSettings } from '../store/useStore'
import { recommendVehicle } from '../data/vehicles'
import { calculateCost, formatCurrency } from '../services/costCalculator'

export default function Estimate() {
  const { id } = useParams<{ id: string }>()
  const nav = useNavigate()
  const { getEstimate, updateEstimate } = useEstimates()
  const { settings } = useSettings()
  const estimate = getEstimate(id!)
  const [expandedRoom, setExpandedRoom] = useState<string | null>(null)

  if (!estimate) return <div className="p-6 text-center text-gray-500">Estimate not found</div>

  const currency = estimate.currency || settings.currency
  const recs = recommendVehicle(estimate.total_volume, estimate.total_weight)
  const costs = calculateCost(estimate)
  const recommended = recs.find(r => r.percentFull > 0 && r.percentFull <= 85) || recs[recs.length - 1]

  const cuftToM3 = (cuft: number) => (cuft * 0.0283168).toFixed(1)
  const kgToLbs = (kg: number) => Math.round(kg * 2.20462)

  const shareWhatsApp = () => {
    const text = `Moving Estimate:\n📦 ${estimate.total_volume} cuft (${cuftToM3(estimate.total_volume)} m³)\n⚖️ ${estimate.total_weight} kg\n🚛 ${estimate.recommended_vehicle}\n💰 ${formatCurrency(costs.low.total, currency)} - ${formatCurrency(costs.high.total, currency)}\n\nGenerated by Moving Estimator`
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`)
  }

  const removeItem = (roomId: string, itemId: string) => {
    const rooms = estimate.rooms.map(r => {
      if (r.id !== roomId) return r
      const items = r.items.filter(i => i.id !== itemId)
      return { ...r, items, item_count: items.length, total_volume: items.reduce((s, i) => s + i.volume_cuft, 0), total_weight: items.reduce((s, i) => s + i.weight_kg, 0) }
    })
    const totalVol = rooms.reduce((s, r) => s + r.total_volume, 0)
    const totalWgt = rooms.reduce((s, r) => s + r.total_weight, 0)
    updateEstimate({ ...estimate, rooms, total_volume: Math.round(totalVol), total_weight: Math.round(totalWgt) })
  }

  return (
    <div className="min-h-screen pb-28">
      {/* Header */}
      <div className="bg-gradient-to-br from-[#1E3A5F] to-[#2A5080] text-white px-6 pt-12 pb-8 rounded-b-3xl">
        <button onClick={() => nav('/')} className="text-blue-200 text-sm mb-4">&larr; Home</button>
        <h1 className="text-xl font-bold">Your Estimate</h1>
        <p className="text-blue-200 text-sm">{estimate.from_city || 'Origin'} → {estimate.to_city || 'Destination'}</p>
      </div>

      <div className="px-5 -mt-4 space-y-4">
        {/* Volume Summary */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          className="bg-white rounded-2xl p-5 shadow-lg">
          <div className="flex items-start gap-4">
            <div className="w-16 h-16 bg-gradient-to-br from-[#FF6B35] to-[#FF8F35] rounded-2xl flex items-center justify-center shadow-lg shadow-orange-200">
              <Box size={28} className="text-white" />
            </div>
            <div className="flex-1">
              <h3 className="text-sm font-medium text-gray-500">Total Volume</h3>
              <p className="text-3xl font-bold text-[#1E3A5F]">{estimate.total_volume} <span className="text-sm font-normal">cuft</span></p>
              <p className="text-xs text-gray-400">{cuftToM3(estimate.total_volume)} m³</p>
            </div>
          </div>
          <div className="grid grid-cols-3 gap-3 mt-4 pt-4 border-t border-gray-100">
            <div className="text-center">
              <p className="text-lg font-bold text-[#1E3A5F]">{estimate.total_weight}</p>
              <p className="text-[10px] text-gray-400">kg ({kgToLbs(estimate.total_weight)} lbs)</p>
            </div>
            <div className="text-center">
              <p className="text-lg font-bold text-[#1E3A5F]">{estimate.rooms.reduce((s, r) => s + r.item_count, 0)}</p>
              <p className="text-[10px] text-gray-400">Items</p>
            </div>
            <div className="text-center">
              <p className="text-lg font-bold text-[#1E3A5F]">{estimate.rooms.length}</p>
              <p className="text-[10px] text-gray-400">Rooms</p>
            </div>
          </div>
        </motion.div>

        {/* Rooms Breakdown */}
        <div>
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wide mb-2">Room Breakdown</h2>
          <div className="space-y-2">
            {estimate.rooms.map(room => (
              <motion.div key={room.id} layout className="bg-white rounded-xl shadow-sm overflow-hidden">
                <button onClick={() => setExpandedRoom(expandedRoom === room.id ? null : room.id)}
                  className="w-full flex items-center justify-between p-4">
                  <div className="flex items-center gap-3">
                    <span className="text-lg">{room.type === 'living_room' ? '🛋️' : room.type === 'master_bedroom' || room.type.startsWith('bedroom') ? '🛏️' : room.type === 'kitchen' ? '🍳' : room.type === 'bathroom' ? '🚿' : room.type === 'office' ? '💼' : '📦'}</span>
                    <div className="text-left">
                      <p className="text-sm font-medium">{room.name}</p>
                      <p className="text-[10px] text-gray-400">{room.item_count} items · {Math.round(room.total_volume)} cuft</p>
                    </div>
                  </div>
                  {expandedRoom === room.id ? <ChevronUp size={16} className="text-gray-400" /> : <ChevronDown size={16} className="text-gray-400" />}
                </button>
                <AnimatePresence>
                  {expandedRoom === room.id && (
                    <motion.div initial={{ height: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }} className="overflow-hidden">
                      <div className="px-4 pb-4 space-y-1.5">
                        {room.items.map(item => (
                          <div key={item.id} className="flex items-center gap-2 bg-gray-50 rounded-lg p-2.5 text-xs">
                            <span className="text-base">{item.icon}</span>
                            <div className="flex-1 min-w-0">
                              <p className="font-medium text-gray-800 truncate">{item.name}</p>
                              <p className="text-[10px] text-gray-400">{item.length_cm}×{item.width_cm}×{item.height_cm}cm · {item.weight_kg}kg</p>
                            </div>
                            <div className="text-right whitespace-nowrap">
                              <p className="font-semibold text-[#1E3A5F]">{item.volume_cuft} cuft</p>
                              <div className="flex items-center gap-1 mt-0.5">
                                <div className="w-8 h-1 bg-gray-200 rounded-full overflow-hidden">
                                  <div className="h-full bg-green-500 rounded-full" style={{ width: `${item.confidence * 100}%` }} />
                                </div>
                                <span className="text-[9px] text-gray-400">{Math.round(item.confidence * 100)}%</span>
                              </div>
                            </div>
                            <button onClick={() => removeItem(room.id, item.id)} className="p-1 text-gray-300 hover:text-red-400">
                              <Trash2 size={12} />
                            </button>
                          </div>
                        ))}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Vehicle Recommendations */}
        <div>
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wide mb-2">Truck Recommendation</h2>
          <div className="space-y-2">
            {recs.map(r => {
              const isRec = r.vehicle.name === recommended.vehicle.name
              return (
                <div key={r.vehicle.id} className={`bg-white rounded-xl p-4 flex items-center gap-3 ${isRec ? 'ring-2 ring-[#FF6B35] shadow-md' : 'shadow-sm'}`}>
                  <span className="text-3xl">{r.vehicle.icon}</span>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-medium truncate">{r.vehicle.name}</p>
                      {isRec && <span className="text-[9px] bg-[#FF6B35] text-white px-1.5 py-0.5 rounded-full font-medium">BEST FIT</span>}
                    </div>
                    <p className="text-[10px] text-gray-400">{r.vehicle.max_volume_cuft} cuft / {r.vehicle.max_weight_kg} kg</p>
                    <div className="w-full h-2 bg-gray-100 rounded-full mt-1.5 overflow-hidden">
                      <div className={`h-full rounded-full transition-all ${r.percentFull > 90 ? 'bg-red-500' : r.percentFull > 70 ? 'bg-orange-500' : 'bg-green-500'}`} style={{ width: `${Math.min(r.percentFull, 100)}%` }} />
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="text-sm font-bold text-[#1E3A5F]">{r.percentFull}%</p>
                    <p className="text-[10px] text-gray-400">{r.trips > 1 ? `${r.trips} trips` : '1 trip'}</p>
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        {/* Cost Estimate */}
        <div>
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wide mb-2">Cost Estimate</h2>
          <div className="bg-white rounded-2xl p-5 shadow-sm">
            <div className="flex items-end justify-between mb-4">
              <div>
                <p className="text-[10px] text-gray-400 uppercase">Estimated Range</p>
                <p className="text-2xl font-bold text-[#1E3A5F]">
                  {formatCurrency(costs.low.total, currency)} <span className="text-sm font-normal text-gray-400">–</span> {formatCurrency(costs.high.total, currency)}
                </p>
              </div>
              <div className="bg-[#FF6B35]/10 rounded-xl px-3 py-1.5">
                <p className="text-[10px] text-[#FF6B35] font-medium">MID ESTIMATE</p>
                <p className="text-sm font-bold text-[#FF6B35]">{formatCurrency(costs.mid.total, currency)}</p>
              </div>
            </div>
            <div className="space-y-2 text-xs">
              {[
                { label: 'Loading & Packing', low: costs.low.loading, mid: costs.mid.loading, high: costs.high.loading },
                { label: 'Transportation', low: costs.low.transport, mid: costs.mid.transport, high: costs.high.transport },
                { label: 'Unloading', low: costs.low.unloading, mid: costs.mid.unloading, high: costs.high.unloading },
                { label: 'Insurance', low: costs.low.insurance, mid: costs.mid.insurance, high: costs.high.insurance },
              ].map(row => (
                <div key={row.label} className="flex items-center justify-between py-1.5 border-b border-gray-50">
                  <span className="text-gray-500">{row.label}</span>
                  <span className="font-medium text-gray-700">{formatCurrency(row.mid, currency)}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Share */}
        <div className="flex gap-2">
          <button onClick={shareWhatsApp} className="flex-1 flex items-center justify-center gap-2 bg-green-500 text-white py-3.5 rounded-xl font-medium text-sm">
            <MessageCircle size={16} /> WhatsApp
          </button>
          <button className="flex-1 flex items-center justify-center gap-2 bg-[#1E3A5F] text-white py-3.5 rounded-xl font-medium text-sm">
            <Mail size={16} /> Email
          </button>
          <button className="flex items-center justify-center gap-2 bg-gray-200 text-gray-700 py-3.5 px-5 rounded-xl font-medium text-sm">
            <Download size={16} />
          </button>
        </div>
      </div>
    </div>
  )
}
